### ISSUE TITLE
event_as_json does not implement countdown field

### ISSUE THREAD

**Issue by rexim** [tsoding/skedudle#66]
introduced in #61
